### ISSUE TITLE
링크 추가 부탁드립니다

### ISSUE THREAD

**Issue by yagom** [ClintJang/awesome-swift-korean-lecture#2]
https://www.inflearn.com/course/ios-프로그래밍/

이 링크도 추가해 주실 수 있을까요? ❤️  :D

**Comment by ClintJang** [comment]
그럼요. 메시지를 보기 전에 이미 링크확인하고 추가했습니다. :)
좋은 정보 고맙습니다.  👍 
항상 yagom 님 목소리 들으며 공부하고 있습니다.  yagom 님 메시지를 보니 너무 기뻤습니다.
늘 감사합니다.  
즐거운 주말 되세요 (꾸벅)

- 상세 내용은 항상 고민하고 더 알기 쉬운 문구나 좋은 생각이 들면 고치고 있습니다.

**Comment by yagom** [comment]
크으 역시 짱입니다요~! 👍  감사할 따름이지요 ❤️
